# DefiSettings represents the set of current settings and limits
# applied to DeFi operations.
type DefiSettings {
    # priceOracleAggregate is the address of the current price oracle
    # aggregate used by the DeFi to obtain USD price of tokens managed.
    priceOracleAggregate: Address!

    # StakeTokenizerContract is the address of the Stake Tokenizer contract.
    StakeTokenizerContract: Address!

    # StakeTokenizedERC20Token is the address of the Tokenized Stake ERC20 contract.
    StakeTokenizedERC20Token: Address!

}
